# Data Wrangling

**Data wrangling, sometimes referred to as data munging, 
is the process of transforming and mapping data from one "raw" data form into another 
format with the intent of making it more appropriate 
and valuable for a variety of downstream purposes such as analytics.**
*Wikipedia*

## Importing data

In [1]:
import pandas as pd
import numpy as np

In [2]:
personality_data = pd.read_csv('personality_scores.csv',sep=';')

In [3]:
personality_data.head()

,ID,Section 5 of 6 [I am always prepared.],Section 5 of 6 [I am easily disturbed.],Section 5 of 6 [I am exacting (demanding) in my work.],Section 5 of 6 [I am full of ideas.],Section 5 of 6 [I am interested in people.],Section 5 of 6 [I am not interested in abstract ideas.],Section 5 of 6 [I am not interested in other people's problems.],Section 5 of 6 [I am not really interested in others.],Section 5 of 6 [I am quick to understand things.],...,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,IPIP_HIGH_RISK
0,0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# personality_data.info()

In [5]:
personality_data.isnull().sum()

ID                                                           0
Section 5 of 6 [I am always prepared.]                       0
Section 5 of 6 [I am easily disturbed.]                      0
Section 5 of 6 [I am exacting (demanding) in my work.]       0
Section 5 of 6 [I am full of ideas.]                         0
                                                          ...
Unnamed: 65                                               1555
Unnamed: 66                                               1555
Unnamed: 67                                               1555
Unnamed: 68                                               1555
IPIP_HIGH_RISK                                            1555
Length: 70, dtype: int64

# Find Duplicate Rows based on selected columns

In [6]:
personality_data.ID.unique()

array([   0,    1,    2, ..., 1552, 1553, 1554])

In [7]:
personality_data[personality_data.duplicated(keep=False)]

Empty DataFrame
Columns: [ID, Section 5 of 6 [I am always prepared.], Section 5 of 6 [I am easily disturbed.], Section 5 of 6 [I am exacting (demanding) in my work.], Section 5 of 6 [I am full of ideas.], Section 5 of 6 [I am interested in people.], Section 5 of 6 [I am not interested in abstract ideas.], Section 5 of 6 [I am not interested in other people's problems.], Section 5 of 6 [I am not really interested in others.], Section 5 of 6 [I am quick to understand things.], Section 5 of 6 [I am quiet around strangers.], Section 5 of 6 [I am relaxed most of the time.], Section 5 of 6 [I am the life of the party.], Section 5 of 6 [I change my mood a lot.], Section 5 of 6 [I do not have a good imagination.], Section 5 of 6 [I don't like to draw attention to myself.], Section 5 of 6 [I don't mind being the center of attention.], Section 5 of 6 [I don't talk a lot.], Section 5 of 6 [I feel comfortable around people.], Section 5 of 6 [I feel little concern for others.], Section 5 of 6 [I feel others' emotions.], Section 5 of 6 [I follow a schedule.], Section 5 of 6 [I get chores done right away.], Section 5 of 6 [I get irritated easily.], Section 5 of 6 [I get stressed out easily.], Section 5 of 6 [I get upset easily.], Section 5 of 6 [I have a rich vocabulary.], Section 5 of 6 [I have a soft (kind) heart.], Section 5 of 6 [I have a vivid imagination.], Section 5 of 6 [I have difficulty understanding abstract ideas.], Section 5 of 6 [I have excellent ideas.], Section 5 of 6 [I have frequent mood swings.], Section 5 of 6 [I have little to say.], Section 5 of 6 [I insult people.], Section 5 of 6 [I keep in the background.], Section 5 of 6 [I leave my belongings lying around.], Section 5 of 6 [I like order.], Section 5 of 6 [I make a mess of things.], Section 5 of 6 [I make people feel at ease.], Section 5 of 6 [I neglect my duties.], Section 5 of 6 [I often feel blue (down).], Section 5 of 6 [I often forget to put things back in their proper place], Section 5 of 6 [I pay attention to details.], Section 5 of 6 [I seldom feel blue (down).], Section 5 of 6 [I spend time reflecting on things.], Section 5 of 6 [I start conversations.], Section 5 of 6 [I sympathize with others' feelings.], Section 5 of 6 [I take time out for others.], Section 5 of 6 [I talk to a lot of different people at parties.], Section 5 of 6 [I use difficult words.], Section 5 of 6 [I worry about things.], Unnamed: 51, Unnamed: 52, Unnamed: 53, Unnamed: 54, Unnamed: 55, Unnamed: 56, Unnamed: 57, Unnamed: 58, Unnamed: 59, Unnamed: 60, Unnamed: 61, Unnamed: 62, Unnamed: 63, Unnamed: 64, Unnamed: 65, Unnamed: 66, Unnamed: 67, Unnamed: 68, IPIP_HIGH_RISK]
Index: []

[0 rows x 70 columns]

In [8]:
personality_data[personality_data['ID'].duplicated() == True]

Empty DataFrame
Columns: [ID, Section 5 of 6 [I am always prepared.], Section 5 of 6 [I am easily disturbed.], Section 5 of 6 [I am exacting (demanding) in my work.], Section 5 of 6 [I am full of ideas.], Section 5 of 6 [I am interested in people.], Section 5 of 6 [I am not interested in abstract ideas.], Section 5 of 6 [I am not interested in other people's problems.], Section 5 of 6 [I am not really interested in others.], Section 5 of 6 [I am quick to understand things.], Section 5 of 6 [I am quiet around strangers.], Section 5 of 6 [I am relaxed most of the time.], Section 5 of 6 [I am the life of the party.], Section 5 of 6 [I change my mood a lot.], Section 5 of 6 [I do not have a good imagination.], Section 5 of 6 [I don't like to draw attention to myself.], Section 5 of 6 [I don't mind being the center of attention.], Section 5 of 6 [I don't talk a lot.], Section 5 of 6 [I feel comfortable around people.], Section 5 of 6 [I feel little concern for others.], Section 5 of 6 [I feel others' emotions.], Section 5 of 6 [I follow a schedule.], Section 5 of 6 [I get chores done right away.], Section 5 of 6 [I get irritated easily.], Section 5 of 6 [I get stressed out easily.], Section 5 of 6 [I get upset easily.], Section 5 of 6 [I have a rich vocabulary.], Section 5 of 6 [I have a soft (kind) heart.], Section 5 of 6 [I have a vivid imagination.], Section 5 of 6 [I have difficulty understanding abstract ideas.], Section 5 of 6 [I have excellent ideas.], Section 5 of 6 [I have frequent mood swings.], Section 5 of 6 [I have little to say.], Section 5 of 6 [I insult people.], Section 5 of 6 [I keep in the background.], Section 5 of 6 [I leave my belongings lying around.], Section 5 of 6 [I like order.], Section 5 of 6 [I make a mess of things.], Section 5 of 6 [I make people feel at ease.], Section 5 of 6 [I neglect my duties.], Section 5 of 6 [I often feel blue (down).], Section 5 of 6 [I often forget to put things back in their proper place], Section 5 of 6 [I pay attention to details.], Section 5 of 6 [I seldom feel blue (down).], Section 5 of 6 [I spend time reflecting on things.], Section 5 of 6 [I start conversations.], Section 5 of 6 [I sympathize with others' feelings.], Section 5 of 6 [I take time out for others.], Section 5 of 6 [I talk to a lot of different people at parties.], Section 5 of 6 [I use difficult words.], Section 5 of 6 [I worry about things.], Unnamed: 51, Unnamed: 52, Unnamed: 53, Unnamed: 54, Unnamed: 55, Unnamed: 56, Unnamed: 57, Unnamed: 58, Unnamed: 59, Unnamed: 60, Unnamed: 61, Unnamed: 62, Unnamed: 63, Unnamed: 64, Unnamed: 65, Unnamed: 66, Unnamed: 67, Unnamed: 68, IPIP_HIGH_RISK]
Index: []

[0 rows x 70 columns]

In [9]:
dups_id=personality_data.pivot_table(index=['ID'],aggfunc='size').sum()

print(dups_id)

1555

## Drop any duplicates that exist

In [10]:

data=personality_data.drop_duplicates(subset=['ID'])

### Comparing the length of the new data frame with old one that may have had duplicates.

*Python's assert statement is a debugging aid that tests a condition.
If the condition is true, it does nothing and your program just continues to execute.
But if the assert condition evaluates to false,
it raises an AssertionError exception with an optional error message.*

*The assert statement should show that the length of unique values of the original 
data is the same as the length of the  data set were duplicates are dropped.*

In [11]:
old_data=len(personality_data.ID.unique())

In [12]:
new_data=len(data)

In [13]:
assert old_data==new_data

In [14]:
print('The length of unique IDs is:',old_data)

The length of unique IDs is: 1555

In [15]:
print('The length of data set after dropping duplicates:',new_data)

The length of data set after dropping duplicates: 1555

*The unique values of old data set has the same length
as the new data set of which is the old data set with dropped duplicate values.*

### Dropping columns with null values

In [16]:
data=data.dropna(axis='columns')
data

,ID,Section 5 of 6 [I am always prepared.],Section 5 of 6 [I am easily disturbed.],Section 5 of 6 [I am exacting (demanding) in my work.],Section 5 of 6 [I am full of ideas.],Section 5 of 6 [I am interested in people.],Section 5 of 6 [I am not interested in abstract ideas.],Section 5 of 6 [I am not interested in other people's problems.],Section 5 of 6 [I am not really interested in others.],Section 5 of 6 [I am quick to understand things.],...,Section 5 of 6 [I often forget to put things back in their proper place],Section 5 of 6 [I pay attention to details.],Section 5 of 6 [I seldom feel blue (down).],Section 5 of 6 [I spend time reflecting on things.],Section 5 of 6 [I start conversations.],Section 5 of 6 [I sympathize with others' feelings.],Section 5 of 6 [I take time out for others.],Section 5 of 6 [I talk to a lot of different people at parties.],Section 5 of 6 [I use difficult words.],Section 5 of 6 [I worry about things.]
0,0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,"(3, 5)","(3, 5)","(4, 3)","(5, 5)","(1, 3)","(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)"
1,1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)",...,"(3, 5)","(3, 1)","(4, 1)","(5, 5)","(1, 5)","(2, 5)","(2, 5)","(1, 5)","(5, 3)","(4, 3)"
2,2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,"(3, 5)","(3, 5)","(4, 1)","(5, 3)","(1, 3)","(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)"
3,3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)",...,"(3, 1)","(3, 5)","(4, 1)","(5, 5)","(1, 5)","(2, 5)","(2, 5)","(1, 5)","(5, 1)","(4, 1)"
4,4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)",...,"(3, 5)","(3, 5)","(4, 5)","(5, 5)","(1, 3)","(2, 3)","(2, 5)","(1, 3)","(5, 1)","(4, 3)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1550,1550,"(3, 5)","(4, 5)","(3, 1)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,"(3, 1)","(3, 5)","(4, 1)","(5, 3)","(1, 5)","(2, 5)","(2, 3)","(1, 1)","(5, 1)","(4, 5)"
1551,1551,"(3, 3)","(4, 5)","(3, 5)","(5, 3)","(2, 5)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,"(3, 3)","(3, 3)","(4, 1)","(5, 3)","(1, 3)","(2, 5)","(2, 5)","(1, 5)","(5, 1)","(4, 3)"
1552,1552,"(3, 5)","(4, 3)","(3, 5)","(5, 5)","(2, 5)","(5, 5)","(2, 3)","(2, 3)","(5, 5)",...,"(3, 3)","(3, 5)","(4, 5)","(5, 5)","(1, 5)","(2, 5)","(2, 5)","(1, 5)","(5, 3)","(4, 3)"
1553,1553,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,"(3, 5)","(3, 5)","(4, 1)","(5, 5)","(1, 5)","(2, 3)","(2, 3)","(1, 1)","(5, 1)","(4, 3)"
1554,1554,"(3, 3)","(4, 5)","(3, 1)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 5)","(5, 3)",...,"(3, 5)","(3, 5)","(4, 3)","(5, 3)","(1, 3)","(2, 5)","(2, 3)","(1, 1)","(5, 1)","(4, 3)"

## converting all the columns into a list

### creating a dictionary

In [17]:
Dict={1:'Extraversion', 2:'Agreeableness', 3:'Conscientiousness',
      4:'Emotional Stability',5:'Intellect'}

In [18]:
data=data.set_index('ID')

In [19]:
list_of_rows=data.values.tolist()

In [20]:
# lis_of_rows=data.values.tolist()
len(list_of_rows)

1555

In [ ]:
data

### creating a function for addition

In [ ]:
p=[]
for l in list_of_rows:
    l=[eval(l[i]) for i in range(len(l))]
    
    totals = {}
    for uid, x in l:
        if uid not in totals :
            totals[uid] = x
        else :
            totals[uid] += x    
    p.append(totals)
    a=pd.DataFrame(p)

In [ ]:
# a.columns = a.columns.to_series().map(Dict)

In [ ]:
a

### merging the dataframes

*merging data and a*

In [ ]:
#  result = pd.concat([data, a], axis=1, ignore_index=True)